#
# Arm SCP/MCP Software
# Copyright (c) 2022, Arm Limited and Contributors. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

BS_LIB_NAME := "PCIE Enumeration"
BS_LIB_SOURCES = mod_pcie_enumeration.c

include $(BS_DIR)/lib.mk
